# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wms_development
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

# remote db for development  
# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   encoding: utf8
#   database: iwm_production
#   username: iwm_production
#   password: iwmdevelopment
#   host: iwm-development.chreexuqvsr9.ap-southeast-2.rds.amazonaws.com
#   port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wms_test
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock
